server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=course_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Harshal@8788

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

aws.access-key=ttt
aws.secret-key=ttt
aws.region=ap-south-1
aws.bucket-name=harshalkadam-s3-bucket